language: objective-c
before_install: gem install cocoapods
script:
  - cd DemoApp
  - pod install
  - xcodebuild -workspace DemoApp.xcworkspace -scheme DemoApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild test -workspace DemoApp.xcworkspace -scheme DemoApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
